#
# This reusable workflow is used to build a TypeScript project, run tests using vitest, and perform SonarCloud analysis.
# It is designed to be called from other workflows.
#
#
# HOW TO USE:
#
# To call this reusable workflow, copy the code between === lines to a new workflow file,
# uncomment and adjust "uses" as needed (use the latest tag available).
# ======================================================================
#
# name: xxxxx
#
# on:
#   pull_request:
#     branches:
#       # every PR targetting main branch
#       - main
#     types:
#       # on labeled and unlabeled to validate labels,
#       # on closed to create tag when PR is merged
#       types: [labeled, unlabeled, closed]
#
# jobs:
#   build-n-test:
#     uses: OutSystems/rd.github-reusable-workflows/.github/workflows/ts-build-project@vVersionHash
#     with:
#         github-ref: ${{ github.ref }}
#         sonarcloud-host-url: ${{ SONAR_HOST_URL }}
#         sonarcloud-org: ${{ SONAR_ORG }}
#
# ======================================================================
#
name: Build TS project
description: 'Build, run Vitest tests, and SonarCloud in a TypeScript project.'
on:
    workflow_call:
        inputs:
            github-ref:
                description: 'GitHub reference to be used as base to create a new one to generate and be published.'
                type: string
                required: true
            sonarcloud-host-url:
                description: 'SonarCloud host URL.'
                type: string
                required: false
                default: 'https://sonarcloud.io'
            sonarcloud-org:
                description: 'SonarCloud organization name.'
                type: string
                required: false
                default: 'outsystemsrd'
            run-vitest:
                description: 'Defines if Vitest tests should be run or not.'
                type: boolean
                required: false
                default: false

concurrency:
    group: ${{ inputs.github-ref }}
    cancel-in-progress: true

jobs:
    build-n-test:
        runs-on: ubuntu-latest
        steps:
            - name: Azure login
              #uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-login@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              uses: .github/actions/az-login
              with:
                  client-id: ${{ secrets.OSUI_AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.OSUI_AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.OSUI_AZURE_SUBSCRIPTION_ID }}

            - name: Get Azure DevOps token
              id: get-devOps-token
              #uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              uses: .github/actions/az-keyvault-get
              with:
                  key-name: o11odc-github-ado-token-prd

            - name: Get SonarCloud token
              id: get-sonarcloud-token
              #uses: OutSystems/rd.github-reusable-workflows/.github/actions/az-keyvault-get@9d497d1c5bc6e355aa8f4663539e6b75c212f6b4 #v2.0.7
              uses: .github/actions/az-keyvault-get
              with:
                  key-name: o11odc-github-sonarcloud-token-prd

            - name: Checkout main branch
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: ${{ inputs.github-ref }}

            - name: â­• Connect to OutSystems Environment
              shell: bash
              run: npx @outsystems/assistant login --token ${{ steps.get-devOps-token.outputs.az-keyvault-value }}

            - name: Install dependencies
              run: npm install

            - name: Run build
              run: npm run build

            - name: Run Vitest with Code Coverage
              if: ${{ inputs.run-vitest == true }}
              run: npm run test:coverage

            - name: Run sonarcloud analysis
              #uses: OutSystems/rd.github-reusable-workflows/.github/actions/run-sonarcloud@3df86e14f6ad0021256077f91c43eca3f73d3b57 #v2.0.6
              uses: .github/actions/run-sonarcloud
              with:
                  sonarcloud-token: ${{ steps.get-sonarcloud-token.outputs.az-keyvault-value }}
                  sonarcloud-host-url: ${{ inputs.sonarcloud-host-url }}
                  sonarcloud-org: ${{ inputs.sonarcloud-org }}
